#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_fprintf_53a41CWE134_Uncontrolled_Format_String__char_console_fprintf_53d29_1(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_53_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_53_bad_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_53a92CWE134_Uncontrolled_Format_String__char_console_fprintf_53d47_1(char *_goodB2G_data_0, void (*opsink)(char *_goodB2G_data_0));
