#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_fprintf_68a55CWE134_Uncontrolled_Format_String__char_file_fprintf_68b40_1(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_68_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_68b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_file_fprintf_68a104CWE134_Uncontrolled_Format_String__char_file_fprintf_68b60_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_68b_goodB2GSink_data_0));
