#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_fprintf_22a43CWE134_Uncontrolled_Format_String__char_console_fprintf_22b34_1(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_22_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_22_bad_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_22a88CWE134_Uncontrolled_Format_String__char_console_fprintf_22b58_1(char *_goodB2G1_data_0, void (*opsink)(char *_goodB2G1_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_22a88CWE134_Uncontrolled_Format_String__char_console_fprintf_22b78_1(char *_goodB2G1_data_0, void (*opsink)(char *_goodG2B_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_22a124CWE134_Uncontrolled_Format_String__char_console_fprintf_22b68_1(char *_goodB2G2_data_0, void (*opsink)(char *_goodB2G2_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_22a124CWE134_Uncontrolled_Format_String__char_console_fprintf_22b78_1(char *_goodB2G2_data_0, void (*opsink)(char *_goodG2B_data_0));
