#include "_costom_header_.h"
void CWE606_Unchecked_Loop_Condition__char_console_51a43CWE606_Unchecked_Loop_Condition__char_console_51b36_1(char *_CWE606_Unchecked_Loop_Condition__char_console_51_bad_data_0, void (*opsink)(int _CWE606_Unchecked_Loop_Condition__char_console_51b_badSink_n_0));
void CWE606_Unchecked_Loop_Condition__char_console_51a94CWE606_Unchecked_Loop_Condition__char_console_51b80_1(char *_goodB2G_data_0, void (*opsink)(int _CWE606_Unchecked_Loop_Condition__char_console_51b_goodB2GSink_n_0));
