#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_printf_1651CWE134_Uncontrolled_Format_String__char_file_printf_1666_1(char *_CWE134_Uncontrolled_Format_String__char_file_printf_16_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_printf_16_bad_data_0));
void CWE134_Uncontrolled_Format_String__char_file_printf_1694CWE134_Uncontrolled_Format_String__char_file_printf_16109_1(char *_goodB2G_data_0, void (*opsink)(char *_goodB2G_data_0));
void CWE134_Uncontrolled_Format_String__char_file_printf_1694CWE134_Uncontrolled_Format_String__char_file_printf_16129_1(char *_goodB2G_data_0, void (*opsink)(char *_goodG2B_data_0));
