#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_vprintf_2157CWE134_Uncontrolled_Format_String__char_console_vprintf_2176_1(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_21_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_21_bad_data_0));
