#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_fprintf_64a51CWE134_Uncontrolled_Format_String__char_file_fprintf_64b39_1(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_64_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_64b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_file_fprintf_64a98CWE134_Uncontrolled_Format_String__char_file_fprintf_64b65_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_64b_goodB2GSink_data_0));
