#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_fprintf_51a51CWE134_Uncontrolled_Format_String__char_file_fprintf_51b35_1(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_51_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_51_bad_data_0));
void CWE134_Uncontrolled_Format_String__char_file_fprintf_51a98CWE134_Uncontrolled_Format_String__char_file_fprintf_51b53_1(char *_goodB2G_data_0, void (*opsink)(char *_goodB2G_data_0));
