#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_fprintf_64a41CWE134_Uncontrolled_Format_String__char_console_fprintf_64b33_1(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_64_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_64b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_64a92CWE134_Uncontrolled_Format_String__char_console_fprintf_64b59_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_64b_goodB2GSink_data_0));
