#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_vprintf_3161CWE134_Uncontrolled_Format_String__char_file_vprintf_3174_1(char *_CWE134_Uncontrolled_Format_String__char_file_vprintf_31_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_vprintf_31_bad_data_1));
