#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_vprintf_4156CWE134_Uncontrolled_Format_String__char_console_vprintf_4141_1(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_41_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_41_bad_data_0));
