#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include "_slice_header_.h"
#include<assert.h>

char* sink_outputarg_0;
char* sink_outputarg_copy_0;

void opsink1(char* arg0)
{
	memcpy(sink_outputarg_0,arg0,strlen(arg0)+1);
}

void opsink2(char* arg0)
{
	memcpy(sink_outputarg_copy_0,arg0,strlen(arg0)+1);
}

void CWE134_Uncontrolled_Format_String__char_console_fprintf_61b35CWE134_Uncontrolled_Format_String__char_console_fprintf_61a36_1_self_com(){
	char sink_outputarg_0arr1[16];
	sink_outputarg_0 = sink_outputarg_0arr1;
	char sink_outputarg_copy_0arr2[16];
	sink_outputarg_copy_0 = sink_outputarg_copy_0arr2;
	memcpy(sink_outputarg_copy_0arr2,sink_outputarg_0arr1,16);
	char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_01;
	char _CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_0arr1[16];
	_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_01 = _CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_0arr1;
	char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_02;
	char _CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_0arr2[16];
	_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_02 = _CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_0arr2;
	memcpy(_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_0arr2,_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_0arr1,16);
	char **CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_1;
	char *CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_ptr1;
	CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_1 = &CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_ptr1;
	char CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_arr1[16];
	CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_ptr1 = CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_arr1;
	char **CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_2;
	char *CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_ptr2;
	CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_2 = &CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_ptr2;
	char CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_arr2[16];
	CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_ptr2 = CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_arr2;
	memcpy(CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_arr2,CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_arr1,16);
	CWE134_Uncontrolled_Format_String__char_console_fprintf_61b35CWE134_Uncontrolled_Format_String__char_console_fprintf_61a36_1(_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_01,CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_1,opsink1);
	CWE134_Uncontrolled_Format_String__char_console_fprintf_61b35CWE134_Uncontrolled_Format_String__char_console_fprintf_61a36_1(_CWE134_Uncontrolled_Format_String__char_console_fprintf_61_bad_data_02,CWE134_Uncontrolled_Format_String__char_console_fprintf_61b_badSource_return_2,opsink2);
	assert(strcmp(sink_outputarg_0,sink_outputarg_copy_0)==0);
}
