#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_fprintf_63a51CWE134_Uncontrolled_Format_String__char_file_fprintf_63b36_1(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_63_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_63b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_file_fprintf_63a98CWE134_Uncontrolled_Format_String__char_file_fprintf_63b56_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_63b_goodB2GSink_data_0));
