#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_environment_printf_0143CWE134_Uncontrolled_Format_String__char_environment_printf_0152_1(char *_CWE134_Uncontrolled_Format_String__char_environment_printf_01_bad_environment_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_environment_printf_01_bad_data_0));
void CWE134_Uncontrolled_Format_String__char_environment_printf_0180CWE134_Uncontrolled_Format_String__char_environment_printf_0189_1(char *_goodB2G_environment_0, void (*opsink)(char *_goodB2G_data_0));
