#include "_costom_header_.h"
void CWE606_Unchecked_Loop_Condition__char_console_52a43CWE606_Unchecked_Loop_Condition__char_console_52c36_1(char *_CWE606_Unchecked_Loop_Condition__char_console_52_bad_data_0, void (*opsink)(int _CWE606_Unchecked_Loop_Condition__char_console_52c_badSink_n_0));
void CWE606_Unchecked_Loop_Condition__char_console_52a94CWE606_Unchecked_Loop_Condition__char_console_52c80_1(char *_goodB2G_data_0, void (*opsink)(int _CWE606_Unchecked_Loop_Condition__char_console_52c_goodB2GSink_n_0));
