#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_fprintf_68a45CWE134_Uncontrolled_Format_String__char_console_fprintf_68b34_1(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_68_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_68b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_68a98CWE134_Uncontrolled_Format_String__char_console_fprintf_68b54_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_68b_goodB2GSink_data_0));
