#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_fprintf_63a41CWE134_Uncontrolled_Format_String__char_console_fprintf_63b30_1(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_63_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_63b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_63a92CWE134_Uncontrolled_Format_String__char_console_fprintf_63b50_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_63b_goodB2GSink_data_0));
