#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_vprintf_4237CWE134_Uncontrolled_Format_String__char_console_vprintf_4275_1(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_42_bad_data_0, char * *badSource_return_, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_42_bad_data_0));
