#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_file_fprintf_66a52CWE134_Uncontrolled_Format_String__char_file_fprintf_66b37_1(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_66_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_66b_badSink_data_0));
void CWE134_Uncontrolled_Format_String__char_file_fprintf_66a104CWE134_Uncontrolled_Format_String__char_file_fprintf_66b57_1(char *_goodB2G_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_file_fprintf_66b_goodB2GSink_data_0));
