#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_vprintf_4561CWE134_Uncontrolled_Format_String__char_console_vprintf_4546_1(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_45_bad_data_0, void (*opsink)(char *_badSink_data_0));
