#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_fprintf_51a41CWE134_Uncontrolled_Format_String__char_console_fprintf_51b29_1(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_51_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_fprintf_51_bad_data_0));
void CWE134_Uncontrolled_Format_String__char_console_fprintf_51a92CWE134_Uncontrolled_Format_String__char_console_fprintf_51b47_1(char *_goodB2G_data_0, void (*opsink)(char *_goodB2G_data_0));
