#include "_costom_header_.h"
void CWE134_Uncontrolled_Format_String__char_console_vprintf_3151CWE134_Uncontrolled_Format_String__char_console_vprintf_3172_1(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_31_bad_data_0, void (*opsink)(char *_CWE134_Uncontrolled_Format_String__char_console_vprintf_31_bad_data_1));
